### ISSUE TITLE
Crasher right on server launch

### ISSUE THREAD

**Issue by posukene** [Artemis-the-gr8/PlayerStatsExpansion#42]
As seen below, plugin is missing something for 1.19.4 paper.
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins\PlayerStatsExpansion-2.0.0.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!

Log:

Loading libraries, please wait...
[01:11:25 ERROR]: [DirectoryProviderSource] Error loading plugin: Directory 'plugins\PlayerStatsExpansion-2.0.0.jar' failed to load!
java.lang.RuntimeException: Directory 'plugins\PlayerStatsExpansion-2.0.0.jar' failed to load!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:59) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.lambda$registerProviders$1(DirectoryProviderSource.java:34) ~[paper-1.19.4.jar:git-Paper-533]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:32) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:14) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:14) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:100) ~[paper-1.19.4.jar:git-Paper-533]
        at net.minecraft.server.Main.main(Main.java:126) ~[paper-1.19.4.jar:git-Paper-533]
        at org.bukkit.craftbukkit.Main.main(Main.java:309) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: plugins\PlayerStatsExpansion-2.0.0.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:95) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[paper-1.19.4.jar:git-Paper-533]
        ... 20 more
Caused by: java.lang.IllegalArgumentException: plugins\PlayerStatsExpansion-2.0.0.jar does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.getPluginName(FileProviderSource.java:104) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.checkUpdate(FileProviderSource.java:76) ~[paper-1.19.4.jar:git-Paper-533]
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:49) ~[paper-1.19.4.jar:git-Paper-533]
        ... 20 more

**Comment by Artemis-the-gr8** [comment]
I think that error is happening because you put the expansion in the plugins folder. If you put it in the plugins/PlaceholderAPI/expansions folder, it should work.

**Comment by posukene** [comment]
Tnx, that solved it.
